CPRT/cprt_rover_24

.github/workflows/lint-and-format.yml

This pull request adds a new GitHub Actions workflow to ensure code quality by performing linting and formatting checks for both Python and JavaScript/TypeScript files. The most important changes include the configuration of the workflow and the specific steps for each language.
GitHub Actions workflow configuration:
* [`.github/workflows/lint-and-format.yml`](diffhunk://#diff-60395b39061839b3177416592202e101e3e9d52394ab5d27ed094d4e771f0245R1-R36): Added a new workflow named "Lint and Format Check" that triggers on push and pull request events for all branches.
Python linting and formatting:
* [`.github/workflows/lint-and-format.yml`](diffhunk://#diff-60395b39061839b3177416592202e101e3e9d52394ab5d27ed094d4e771f0245R1-R36): Added steps to install Python dependencies, run Black for …

ROVER-119: Linting and Formatting Workflow Configured

---

.gitmodules

This PR adds 3 git sub modules:
- My own fork of the elevation_mapping repo from Anybotics, but using the version from Muhammad540 and others who ported it to ros2
- The kindr_ros repo since the elevation_mapping is dependent on it
- The zed ros2 wrapper
I'm not sure the desired directory structure we want, I'm open to moving these around if it's possible. The elevation_mapping and kindr_ros repos fit under localization. 
The zed ros2 wrapper should exist on its own since I think it will be used by more things.
Image of what the elevation_mapping produces:

Add elevation_mapping, kindr_ros and zed ros2 wrapper repos

---

.clang-format
.github/workflows/lint-and-format.yml
build.sh
src/ros_phoenix_humble/include/ros_phoenix/base_node.hpp
src/ros_phoenix_humble/include/ros_phoenix/phoenix_bridge.hpp
src/ros_phoenix_humble/include/ros_phoenix/phoenix_components.hpp
src/ros_phoenix_humble/include/ros_phoenix/phoenix_manager.hpp
src/ros_phoenix_humble/include/ros_phoenix/phoenix_node.hpp
src/ros_phoenix_humble/include/ros_phoenix/phoenix_nodes.hpp
src/ros_phoenix_humble/include/ros_phoenix/phoenix_system.hpp
src/ros_phoenix_humble/src/base_node.cpp
src/ros_phoenix_humble/src/phoenix_bridge.cpp
src/ros_phoenix_humble/src/phoenix_container.cpp
src/ros_phoenix_humble/src/phoenix_manager.cpp
src/ros_phoenix_humble/src/phoenix_nodes.cpp
src/ros_phoenix_humble/src/phoenix_system.cpp

We are now writing stuff in c++, we need a formater. I used google's style guide. If you prefer LLVM or GNU I can switch it. The first commit is the formatter setup, the second commit is using the formatter.

Clang format

---

.gitignore
firstTimeInstall.sh
src/interfaces/CMakeLists.txt
src/interfaces/msg/GasSensorReading.msg
src/science_sensors/launch/gas_sensor.launch.py
src/science_sensors/package.xml
src/science_sensors/science_sensors/gas_sensor.py
src/science_sensors/setup.cfg
src/science_sensors/setup.py
src/science_sensors/test/test_copyright.py
src/science_sensors/test/test_flake8.py
src/science_sensors/test/test_pep257.py

Add a node that publishes measurements from the BME280/ENS160 combined sensor according to [ROVER-341].
This has been tested on the Jetson already.

[ROVER-341] Add Life Detection Gas Sensor ROS2 Node

---

.gitmodules
firstTimeInstall.sh
src/arm_interface/package.xml
src/drive/package.xml
src/gps/config/gps.yaml
src/gps/gps/rtcm_pub_node.py
src/gps/gps/ubx_io_manager.py
src/gps/launch/basestation.launch.py
src/gps/launch/rover.launch.py
src/gps/package.xml
src/gps/setup.cfg
src/gps/setup.py
src/gps/test/test_copyright.py
src/gps/test/test_flake8.py
src/gps/test/test_pep257.py
src/localization/config/navsat.yaml
src/localization/launch/gps.launch.py
src/localization/package.xml

This pull request provides GPS with RTK base station functionality. It has been tested for functionality and ensureing the RTCM messages are being read and interpreted and the accuracy increases when the RTK is enabled. According to the NAVPVT information our accuracy fluctuates between 20-30 cm. This was with a 10 minute survey in. More extensive turning of parameters could increase accuracy.
* Added a new GPS submodule `src/gps/ublox` to the project. This submodule is sourced from `https://github.com/KumarRobotics/ublox.git`.
* Updated `firstTimeInstall.sh` to include the installation of the `pyubx2` package, which is necessary for handling UBX messages.
* Implemented a new ROS 2 node `RtcmNode` in `src/gps/gps/rtcm_pub_node.py` for managing RTCM data via serial communication. This node …

Connor gps

---

src/localization/launch/rtabmap.launch.py

i have change the rtabmap.launch.py file in the loclization so it can work with zed2i camera. the change includes remapping into the right topic and some parameter change

configuring rtabmap

---

src/camera_streaming/config/webrtc.yaml

Easiest pull request you will ever review :)
Includes the path for the new main camera and one of our older cheaper cameras. We will add more cameras as we finalize camera locations.

add new camera paths

---

src/drive/launch/talonDrive.launch.py
src/drive_cpp/src/TalonDriveController.cpp
src/drive_cpp/src/WheelControl.cpp

This is the PID values used on the canal and it worked pretty well until the cold froze up the motors. Future refinement maybe needed based on addtional weight (Eg: with Arm) or different terrain.

feat: velocity drive

---

src/drive/launch/xbox_drive.launch.py

Simple launch file that connects to the xbox controller. A better structure to get the two launch files to share stuff can happen later

Mech guys launch file

---

src/camera_controller/setup.py
src/hardware/package.xml
src/keyboard_publisher/package.xml
src/moveit_controller/package.xml
src/science_sensors/package.xml

Some issues with the build dependancies on recent merges. Make sure to use package.xml to include needed dependancies. :)

chore: fix build dependancies

---

src/camera_controller/setup.py

Since I gave you a massive PR to review over in the navigation side. I figured I would give you a freebee :)

fix: import error

---

src/interfaces/CMakeLists.txt
src/interfaces/msg/SystemTelemetry.msg
src/system-telemetry-cpp/CMakeLists.txt
src/system-telemetry-cpp/LICENSE
src/system-telemetry-cpp/include/system-telemetry-cpp/cpu_collector.hpp
src/system-telemetry-cpp/include/system-telemetry-cpp/gpu_collector.hpp
src/system-telemetry-cpp/include/system-telemetry-cpp/memory_collector.hpp
src/system-telemetry-cpp/include/system-telemetry-cpp/system_telemetry_publisher.hpp
src/system-telemetry-cpp/include/system-telemetry-cpp/telemetry_collector.hpp
src/system-telemetry-cpp/package.xml
src/system-telemetry-cpp/src/cpu_collector.cpp
src/system-telemetry-cpp/src/gpu_collector.cpp
src/system-telemetry-cpp/src/memory_collector.cpp
src/system-telemetry-cpp/src/system_telemetry_publisher.cpp

Just a package to publish system statistics. Provides a nice modular framework to do so for more messages along the road. 
Current stats collected and published are:
- mmry
- gpu
- cpu

feat: add framework for publishing system telemetry

---

src/drive/launch/flightstick_drive.launch.py
src/drive/setup.py
src/joystick_control/src/FlightstickControl.cpp

Emergency fix to drive launch files

fix: import errors

---

src/arm_interface/launch/talon.launch.py
src/arm_interface/package.xml
src/arm_interface/setup.cfg
src/arm_interface/setup.py
src/arm_interface/test/test_copyright.py
src/arm_interface/test/test_flake8.py
src/arm_interface/test/test_pep257.py
src/drive/config/pxn.yaml
src/drive/launch/flightstick_drive.launch.py
src/drive/launch/talon.launch.py
src/joystick_control/CMakeLists.txt
src/joystick_control/include/joystick_control/ArmManualMode.hpp
src/joystick_control/include/joystick_control/FlightstickControl.hpp
src/joystick_control/src/ArmManualMode.cpp
src/joystick_control/src/FlightstickControl.cpp
src/servo_pkg/launch/usb_servo_launch.launch.py

Added 'manual_mode' to the behaviours. Tested off rover and works as expected, fine tuning may be required at a later date.

Manual mode

---

src/moveit_controller/src/servo_keyboard.cpp
src/moveit_controller/src/servo_keyboard.h

There's already a keyboard servo controller in main, and now it can control orientation of the end effector too.

Working keyboard rotations

---

setup/setup_science.sh
setup/start_science.service
setup/start_science.sh

Bash scripts to setup dependancies for our science module raspberry pi

chore: science setup

---

src/computer_vision/computer_vision/zed_aruco_detector.py
src/computer_vision/launch/aruco_detector_zed.launch.py
src/computer_vision/package.xml
src/computer_vision/setup.cfg
src/computer_vision/setup.py
src/computer_vision/test/test_copyright.py
src/computer_vision/test/test_flake8.py
src/computer_vision/test/test_pep257.py

Detects aruco tags with the zed camera and uses the depth map from the zed to get a better estimate.
Publishes a array of poses to help visualize in rviz.
Publishes a ArucoMarkers message which is defined in the interfaces package.

Detect aruco tags with the zed camera

---

src/drive/launch/talon.launch.py
src/drive_cpp/include/drive_cpp/TalonDriveController.hpp
src/drive_cpp/src/TalonDriveController.cpp
src/localization/config/urdf/spike.urdf.xml
src/navigation/config/elevation_mapping/postprocessing_traversability.yaml
src/navigation/config/zed/zed_override_params.yaml
src/navigation/params/nav2.yaml

This pull request introduces several changes across multiple files to update motor configurations, enhance navigation parameters, and improve performance. The most significant updates include reassigning motor IDs in `talon.launch.py`, adding a low-latency mode for the Talon Drive Controller, adjusting navigation parameters for better control and efficiency, and modifying configuration files for localization and elevation mapping.
* Reassigned motor IDs for `frontLeft`, `backLeft`, `frontRight`, and `backRight` in `src/drive/launch/talon.launch.py` to new values: 3, 4, 1, and 2, respectively. [[1]](diffhunk://#diff-8d6003ee0136180a5fd5f2224a9e85f661a5c458821d4207adc9de0017864c30L30-R30) [[2]](diffhunk://#diff-8d6003ee0136180a5fd5f2224a9e85f661a5c458821d4207adc9de0017864c30L44-R44) …

Nav tuning

---

setup/cprt_bash_aliases.sh
setup/cprt_bash_rc.sh
setup/firstTimeInstall.sh
setup/restart_all_usb_ports.sh
src/navigation/rviz/nav2_cprt.rviz
src/navigation/rviz/nav2_offical_default_config.rviz

Add bash aliases file which is sourced by a CPRT bash rc file which is sourced by the real bash rc file.
Also has a helper function to make aliases that will echo the command and then run it so we know what is being run.

Add bash aliases script

---

src/drive/config/pxn.yaml
src/joystick_control/src/ArmIKMode.cpp
src/joystick_control/src/ArmManualMode.cpp
src/servo_pkg/config/usb_controller.yaml
src/servo_pkg/servo_pkg/USB_Servo.py

Fixed the claw ranges and added a simple forwards and backwards for the manual mode. Inverse frames no longer get stuck in base view.

Arm adjustments

---

setup/install_ros_humble.sh
src/camera_streaming/config/webrtc.yaml
src/camera_streaming/gst-plugins/gstarucomarker.cpp
src/camera_streaming/include/camera_streaming/webrtc_node.h
src/camera_streaming/src/webrtc_node.cpp

Adds the aruco tag detector to our gstreamer pipeline. Initial testing looks good. Will need more testing in the dark

Aruco integration

---

src/bringup/launch/science.launch.py
src/science_sensors/launch/can_module_reader.launch.py
src/science_sensors/package.xml
src/science_sensors/science_sensors/can_module_sensor.py
src/science_sensors/setup.py

Reader that reads the science sensor board output and publishes it to a ros2 topic(s)

Science sensors via can

---

src/arm_srdf/config/arm_urdf.ros2_control.xacro

Encoder cal
